shell.executable("/bin/bash")
shell.prefix("source ~/.bashrc;")

configfile: "config.json"

rule all:
    input:
        expand("csv/n{n}_cnt{cnt}_k{k}.csv", n=config["n"], cnt=config["cnt"],k=config["k"])

rule smurf:
    output: "csv/n{n}_cnt{cnt}_k{k}.csv"
    benchmark: "bench/n{n}_cnt{cnt}_k{k}.bench"
    shell:
        "R CMD BATCH --no-save --no-restore '--args {wildcards.n} {wildcards.cnt} {wildcards.k} {output}' " 
        "sim1.R log/n{wildcards.n}_cnt{wildcards.cnt}_k{wildcards.k}.Rout"
